name: AWS Lambda Zip Deploy - Python
author: Qubitro
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  requirements_txt:
    description: the name/path to the requirements.txt file
    required: true
    default: 'requirements.txt'
  lambda_layer_arn:
    description: The ARN for the Lambda layer the dependencies should be pushed to without the version (every push is a new version).
    required: true
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
  lambda_region:
    description: The Lambda region. Check the AWS docs/readme for examples.
    required: true
  exclude_botocore:
    description: 'Set to "true" to exclude botocore to reduce dependencies layer size. NOTE: This is not recommended https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/'
    required: true
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements_txt }}
    - ${{ inputs.lambda_layer_arn }}
    - ${{ inputs.lambda_function_name }}
    - ${{ inputs.lambda_region }}
    - ${{ inputs.exclude_botocore }}
branding:
  icon: 'cloud-lightning'
  color: 'white'